/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_usc_languagedetectors_CLD2DetectorJNI */

#ifndef _Included_edu_usc_languagedetectors_CLD2DetectorJNI
#define _Included_edu_usc_languagedetectors_CLD2DetectorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_usc_languagedetectors_CLD2DetectorJNI
 * Method:    detectLanguage
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_usc_languagedetectors_CLD2DetectorJNI_detectLanguage
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
